name: Reader3App
options:
  bundleIdPrefix: reader3app
  deploymentTarget:
    iOS: "15.0"

settings:
  SWIFT_OBJC_BRIDGING_HEADER: Reader3App/DZMeBookRead/other/DZMeBookRead-Bridging-Pch.h
  HEADER_SEARCH_PATHS:
    - Reader3App/DZMeBookRead/other
    - Reader3App/DZMeBookRead/other/thirdParty/ASValueTrackingSlider
    - Reader3App/DZMeBookRead/other/thirdParty/DZMCoverController
    - Reader3App/DZMeBookRead/other/thirdParty/DZMMagnifierView
    - Reader3App/DZMeBookRead/other/thirdParty/DZMSegmentedControl
    - Reader3App/DZMeBookRead/other/thirdParty/FDFullscreenPopGesture

targets:
  Reader3App:
    type: application
    platform: iOS
    sources:
      - path: Reader3App
    settings:
      base:
        INFOPLIST_FILE: Reader3App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: reader3app.Reader3App
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
